In [70]:
print("Numpy arrays")


Numpy arrays


In [16]:
#checking numpy is install we use if there is no error then the numpy ia already installed ind sysytem if there is error then numpy is not installed 
#for installing numpy we go to cmd and write pip install numpy
import numpy
import numpy as np
x = np.array([1,2,3,4,])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [35]:
#list
y =[1,2,3,4]
#we print the y
print(y)
#for what type list it is we use type
print(type(y))

[1, 2, 3, 4]
<class 'list'>


In [34]:
#if we have to know how much single line take time to excute we % time it
#if we have know how much whole progrom took for excution we use %% time it 
%timeit [j**4 for j in range(1,9)]

1.66 µs ± 108 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [40]:
#creating array

import numpy as np
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [47]:
#if we have to write array in the starting we use only not print(a)
import numpy as np
a = np.array([1,2,3])
a

array([1, 2, 3])

In [48]:
#if we have to check what type of array it is we use typr 
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(type(a))


[1 2 3 4]
<class 'numpy.ndarray'>


In [69]:
#1D Array [1 2 3 4]    | 
#2D Array[[1 2 3 4]]   |----#ndim is used to check dimension of the array
#3D Array[[[1 2 3 4]]] |

import numpy as np 
ar1 = np.array([1,2,3,4])
print(ar1)
print(ar1.ndim)

import numpy as np
ar2 = np.array([[1,2,3,4],[1,2,3,4]])
print(ar2)
print(ar2.ndim)

import numpy as np
ar3 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(ar3)
print(ar3.ndim)




[1 2 3 4]
1
[[1 2 3 4]
 [1 2 3 4]]
2
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3
